# Generated by Django 5.0.4 on 2024-07-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=200)),
                ('Title', models.CharField(max_length=200)),
                ('Value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AppData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AppId', models.IntegerField(default=0)),
                ('StatusId', models.IntegerField(default=0)),
                ('Created', models.DateTimeField(auto_now=True)),
                ('CreatedBy', models.IntegerField(default=0)),
                ('Modified', models.DateTimeField(auto_now=True)),
                ('ModifiedBy', models.DateTimeField(auto_now=True)),
                ('S1', models.TextField()),
                ('S2', models.TextField()),
                ('S3', models.TextField()),
                ('S4', models.TextField()),
                ('S5', models.TextField()),
                ('S6', models.TextField()),
                ('S7', models.TextField()),
                ('S8', models.TextField()),
                ('S9', models.TextField()),
                ('S10', models.TextField()),
                ('S11', models.TextField()),
                ('S12', models.TextField()),
                ('S13', models.TextField()),
                ('S14', models.TextField()),
                ('S15', models.TextField()),
                ('S16', models.TextField()),
                ('S17', models.TextField()),
                ('S18', models.TextField()),
                ('S19', models.TextField()),
                ('S20', models.DateTimeField(auto_now=True)),
                ('D1', models.DateTimeField(auto_now=True)),
                ('D2', models.DateTimeField(auto_now=True)),
                ('D3', models.DateTimeField(auto_now=True)),
                ('D4', models.DateTimeField(auto_now=True)),
                ('D5', models.DateTimeField(auto_now=True)),
                ('D6', models.DateTimeField(auto_now=True)),
                ('D7', models.DateTimeField(auto_now=True)),
                ('D8', models.DateTimeField(auto_now=True)),
                ('D9', models.DateTimeField(auto_now=True)),
                ('D10', models.DateTimeField(auto_now=True)),
                ('U1', models.IntegerField(default=0)),
                ('U2', models.IntegerField(default=0)),
                ('U3', models.IntegerField(default=0)),
                ('U4', models.IntegerField(default=0)),
                ('U5', models.IntegerField(default=0)),
                ('G1', models.IntegerField(default=0)),
                ('G2', models.IntegerField(default=0)),
                ('G3', models.IntegerField(default=0)),
                ('G4', models.IntegerField(default=0)),
                ('G5', models.IntegerField(default=0)),
                ('N1', models.FloatField(default=0.0)),
                ('N2', models.FloatField(default=0.0)),
                ('N3', models.FloatField(default=0.0)),
                ('N4', models.FloatField(default=0.0)),
                ('N5', models.FloatField(default=0.0)),
                ('N6', models.FloatField(default=0.0)),
                ('N7', models.FloatField(default=0.0)),
                ('N8', models.FloatField(default=0.0)),
                ('N9', models.FloatField(default=0.0)),
                ('N10', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='AppFileds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AppFlow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FromStatus', models.IntegerField(default=0)),
                ('ActionByType', models.CharField(max_length=200)),
                ('ActionBy', models.IntegerField(default=0)),
                ('Action', models.CharField(max_length=200)),
                ('ToStatus', models.IntegerField(default=0)),
                ('CustomAction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AppStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AppId', models.IntegerField(default=0)),
                ('Status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AppList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('create_goup_id', models.CharField(max_length=200)),
                ('access', models.TextField(default='')),
                ('comment', models.TextField(default='')),
                ('comment1', models.TextField(default='')),
                ('filelds', models.ManyToManyField(related_name='appFileds', to='App.appfileds')),
            ],
        ),
    ]
