# Generated by Django 5.0.4 on 2024-07-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_title_appconfig_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appfileds',
            old_name='AppId',
            new_name='app_id',
        ),
        migrations.AddField(
            model_name='appfileds',
            name='db_filed',
            field=models.CharField(default='', max_length=200),
        ),
    ]
