# Generated by Django 5.0.4 on 2024-07-12 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_rename_appid_appfileds_app_id_appfileds_db_filed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appfileds',
            old_name='db_filed',
            new_name='db_field',
        ),
    ]
