# Generated by Django 5.0.4 on 2024-07-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_rename_db_filed_appfileds_db_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appflow',
            old_name='action_by',
            new_name='action_by_filed',
        ),
        migrations.AddField(
            model_name='appflow',
            name='action_by_grp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appflow',
            name='app_id',
            field=models.IntegerField(default=0),
        ),
    ]
