# Generated by Django 5.0.4 on 2024-07-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_rename_action_by_appflow_action_by_filed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appflow',
            name='action_by_filed',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='appflow',
            name='action_by_grp',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
