# Generated by Django 5.0.4 on 2024-07-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_appfileds_order_appflow_order_appstatus_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='appfileds',
            name='access',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
