# Generated by Django 5.0.4 on 2024-07-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_appfileds_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppAccess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app_id', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=600)),
                ('status', models.CharField(max_length=600)),
                ('type', models.CharField(max_length=600)),
                ('group', models.CharField(max_length=600)),
                ('action_by_filed', models.CharField(max_length=600)),
                ('field', models.IntegerField(default=0, null=True)),
                ('access', models.CharField(max_length=600)),
            ],
        ),
    ]
