# Generated by Django 5.0.4 on 2024-07-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_appaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appaccess',
            name='action_by_filed',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='appaccess',
            name='group',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
