# Generated by Django 5.0.4 on 2024-07-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_appaccess_action_by_filed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appfileds',
            name='access',
            field=models.IntegerField(default=0),
        ),
    ]
